name: CI Pipeline

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Увеличиваем общий таймаут
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
    
    - name: Install dependencies
      run: sudo apt-get install -y make
    
    - name: Install golangci-lint
      run: |
        # Установка последней версии с кэшированием
        GOLANGCI_LINT_VERSION=v1.58.0
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
        sh -s -- -b $(go env GOPATH)/bin $GOLANGCI_LINT_VERSION
        
    - name: Run linter
      run: |
        # Увеличиваем таймаут линтера и включаем кэширование
        golangci-lint run --timeout 5m --issues-exit-code=0 -v
        
    - name: Run unit tests
      run: go test -race -count=100 -v ./...
      
    - name: Build
      run: go build -o banner-rotation ./cmd