name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      # Сервис PostgreSQL
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: rotation_user
          POSTGRES_PASSWORD: rotation_pass
          POSTGRES_DB: banner_rotation
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      # Сервис Zookeeper
      zookeeper:
        image: bitnami/zookeeper:latest
        env:
          ALLOW_ANONYMOUS_LOGIN: "yes"
        ports:
          - 2181:2181
      
      # Сервис Kafka
      kafka:
        image: wurstmeister/kafka:latest
        env:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CREATE_TOPICS: "banner_events:1:1"
        ports:
          - 9092:9092
        depends_on:
          - zookeeper

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    
    - name: Install golangci-lint
      run: |
        sudo curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.0
        
    - name: Run linter
      run: golangci-lint run
      
    - name: Run tests
      env:
        DB_URL: "postgres://rotation_user:rotation_pass@localhost:5432/banner_rotation?sslmode=disable"
        KAFKA_BROKERS: "localhost:9092"
        KAFKA_TOPIC: "banner_events"
      run: |
        # Ждем готовности PostgreSQL
        while ! nc -z localhost 5432; do sleep 1; done
        
        # Ждем готовности Kafka
        while ! nc -z localhost 9092; do sleep 1; done
        
        # Запускаем тесты
        go test -race -count=100 -v ./...
      
    - name: Build
      run: go build -o banner-rotation ./cmd