name: CI Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential
      
    - name: Install golangci-lint
      run: |
        # Установка последней версии golangci-lint
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.0
        
    - name: Run linter
      run: |
        # Увеличиваем таймаут линтера
        golangci-lint run --timeout 5m -v
      
    - name: Run tests
      run: |
        # Уменьшаем количество итераций для тестов
        go test -race -count=1 -v ./...
      
    - name: Build
      run: go build -o banner-rotation ./cmd 